import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL("https://plisowski.dev"),
  title: {
    default: "Pawel Lisowski | Senior Software Engineer in Gdynia, Poland",
    template: "%s | Pawel Lisowski",
  },
  description:
    "Pawel Lisowski - Senior Software Engineer based in Gdynia, Poland. 8+ years of experience building scalable full-stack web applications with React, TypeScript, Java, Python, and Next.js. Currently at Novartis.",
  keywords: [
    "Pawel Lisowski",
    "Software Engineer",
    "Senior Software Engineer",
    "Full Stack Developer",
    "Gdynia",
    "Poland",
    "React Developer",
    "TypeScript",
    "Java",
    "Spring Boot",
    "Python",
    "Next.js",
    "Frontend Developer",
    "Backend Developer",
    "Web Developer Gdynia",
    "Programista Gdynia",
  ],
  authors: [{ name: "Pawel Lisowski", url: "https://plisowski.dev" }],
  creator: "Pawel Lisowski",
  publisher: "Pawel Lisowski",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  alternates: {
    canonical: "https://plisowski.dev",
  },
  openGraph: {
    title: "Pawel Lisowski | Senior Software Engineer in Gdynia",
    description:
      "Senior Software Engineer based in Gdynia, Poland with 8+ years of experience building scalable full-stack web applications.",
    url: "https://plisowski.dev",
    siteName: "Pawel Lisowski - Portfolio",
    locale: "en_US",
    type: "website",
    // Images are auto-generated by opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "Pawel Lisowski | Senior Software Engineer",
    description:
      "Senior Software Engineer in Gdynia, Poland. React, TypeScript, Java, Python.",
    // Images are auto-generated by twitter-image.tsx
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  verification: {
    // Add your Google Search Console verification code here
    // google: "your-verification-code",
  },
};

// JSON-LD structured data for SEO
const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Person",
      "@id": "https://plisowski.dev/#person",
      name: "Pawel Lisowski",
      givenName: "Pawel",
      familyName: "Lisowski",
      url: "https://plisowski.dev",
      image: "https://plisowski.dev/images/profile-optimized.webp",
      jobTitle: "Senior Software Engineer",
      worksFor: {
        "@type": "Organization",
        name: "Novartis",
        url: "https://www.novartis.com",
      },
      address: {
        "@type": "PostalAddress",
        addressLocality: "Gdynia",
        addressRegion: "Pomeranian",
        addressCountry: "Poland",
      },
      sameAs: [
        "https://github.com/anpaaan",
        "https://linkedin.com/in/paweljlisowski",
      ],
      knowsAbout: [
        "React",
        "TypeScript",
        "JavaScript",
        "Java",
        "Spring Boot",
        "Python",
        "Next.js",
        "Node.js",
        "PostgreSQL",
        "AWS",
        "Docker",
        "Kubernetes",
      ],
      description:
        "Senior Software Engineer based in Gdynia, Poland with 8+ years of experience building scalable full-stack web applications.",
    },
    {
      "@type": "WebSite",
      "@id": "https://plisowski.dev/#website",
      url: "https://plisowski.dev",
      name: "Pawel Lisowski - Portfolio",
      description: "Personal portfolio of Pawel Lisowski, Senior Software Engineer",
      publisher: {
        "@id": "https://plisowski.dev/#person",
      },
    },
    {
      "@type": "WebPage",
      "@id": "https://plisowski.dev/#webpage",
      url: "https://plisowski.dev",
      name: "Pawel Lisowski | Senior Software Engineer in Gdynia, Poland",
      isPartOf: {
        "@id": "https://plisowski.dev/#website",
      },
      about: {
        "@id": "https://plisowski.dev/#person",
      },
      description:
        "Portfolio website of Pawel Lisowski, a Senior Software Engineer based in Gdynia, Poland.",
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth overflow-x-hidden">
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body
        className={`${inter.variable} ${jetbrainsMono.variable} antialiased overflow-x-hidden`}
      >
        <div className="w-full max-w-full overflow-x-hidden">
          {children}
        </div>
      </body>
    </html>
  );
}
